### ISSUE TITLE
malformed recovery.fstab line 

### ISSUE THREAD

**Issue by sooorajjj** [TeamWin/android_device_yu_tomato#1]
running:  unzip -o -q /home/sooraj/Desktop/Slimkat/out/target/product/tomato/obj/PACKAGING/target_files_intermediates/slim_tomato-target_files-eng.sooraj.zip -d /tmp/targetfiles-iJqNKV
Traceback (most recent call last):
  File "./build/tools/releasetools/ota_from_target_files", line 1121, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/ota_from_target_files", line 1064, in main
    OPTIONS.info_dict = common.LoadInfoDict(input_zip)
  File "/home/sooraj/Desktop/Slimkat/build/tools/releasetools/common.py", line 155, in LoadInfoDict
    d["fstab"] = LoadRecoveryFSTab(zip, d["fstab_version"])
  File "/home/sooraj/Desktop/Slimkat/build/tools/releasetools/common.py", line 227, in LoadRecoveryFSTab
    raise ValueError("malformed recovery.fstab line: \"%s\"" % (line,))
ValueError: malformed recovery.fstab line: "/system       ext4          /dev/block/bootdevice/by-name/system"
make: **\* [/home/sooraj/Desktop/Slimkat/out/target/product/tomato/slim_tomato-ota-eng.sooraj.zip] Error 1

**Comment by sooorajjj** [comment]
while building slimkat

**Comment by Dees-Troy** [comment]
For building TWRP for the Yu Yureka ONLY

That means it's ONLY for building TWRP and not intended to be used for building a ROM. It will require reverts / changes to be able to build a ROM.

**Comment by sooorajjj** [comment]
oh ok thanks :smiley:
